# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/paul/.local/bin/clion-2020.3.2/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/paul/.local/bin/clion-2020.3.2/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/paul/qtcreator_project/dvkbuntu-easy-menu-qt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/paul/qtcreator_project/dvkbuntu-easy-menu-qt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/paul/.local/bin/clion-2020.3.2/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/paul/.local/bin/clion-2020.3.2/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paul/qtcreator_project/dvkbuntu-easy-menu-qt/CMakeFiles /home/paul/qtcreator_project/dvkbuntu-easy-menu-qt//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paul/qtcreator_project/dvkbuntu-easy-menu-qt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dvkbuntu-easy-menu-qt

# Build rule for target.
dvkbuntu-easy-menu-qt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dvkbuntu-easy-menu-qt
.PHONY : dvkbuntu-easy-menu-qt

# fast build rule for target.
dvkbuntu-easy-menu-qt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/build
.PHONY : dvkbuntu-easy-menu-qt/fast

#=============================================================================
# Target rules for targets named dvkbuntu-easy-menu-qt_autogen

# Build rule for target.
dvkbuntu-easy-menu-qt_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dvkbuntu-easy-menu-qt_autogen
.PHONY : dvkbuntu-easy-menu-qt_autogen

# fast build rule for target.
dvkbuntu-easy-menu-qt_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt_autogen.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt_autogen.dir/build
.PHONY : dvkbuntu-easy-menu-qt_autogen/fast

dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.o: dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.cpp.o

.PHONY : dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.o

# target to build an object file
dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.cpp.o
.PHONY : dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.cpp.o

dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.i: dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.cpp.i

.PHONY : dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.i

# target to preprocess a source file
dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.cpp.i
.PHONY : dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.cpp.i

dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.s: dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.cpp.s

.PHONY : dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.s

# target to generate assembly for a file
dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.cpp.s
.PHONY : dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.cpp.s

dvkbuntu-easy-menu-qt_autogen/mocs_compilation.o: dvkbuntu-easy-menu-qt_autogen/mocs_compilation.cpp.o

.PHONY : dvkbuntu-easy-menu-qt_autogen/mocs_compilation.o

# target to build an object file
dvkbuntu-easy-menu-qt_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/dvkbuntu-easy-menu-qt_autogen/mocs_compilation.cpp.o
.PHONY : dvkbuntu-easy-menu-qt_autogen/mocs_compilation.cpp.o

dvkbuntu-easy-menu-qt_autogen/mocs_compilation.i: dvkbuntu-easy-menu-qt_autogen/mocs_compilation.cpp.i

.PHONY : dvkbuntu-easy-menu-qt_autogen/mocs_compilation.i

# target to preprocess a source file
dvkbuntu-easy-menu-qt_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/dvkbuntu-easy-menu-qt_autogen/mocs_compilation.cpp.i
.PHONY : dvkbuntu-easy-menu-qt_autogen/mocs_compilation.cpp.i

dvkbuntu-easy-menu-qt_autogen/mocs_compilation.s: dvkbuntu-easy-menu-qt_autogen/mocs_compilation.cpp.s

.PHONY : dvkbuntu-easy-menu-qt_autogen/mocs_compilation.s

# target to generate assembly for a file
dvkbuntu-easy-menu-qt_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/dvkbuntu-easy-menu-qt_autogen/mocs_compilation.cpp.s
.PHONY : dvkbuntu-easy-menu-qt_autogen/mocs_compilation.cpp.s

src/controlmenu.o: src/controlmenu.cpp.o

.PHONY : src/controlmenu.o

# target to build an object file
src/controlmenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/controlmenu.cpp.o
.PHONY : src/controlmenu.cpp.o

src/controlmenu.i: src/controlmenu.cpp.i

.PHONY : src/controlmenu.i

# target to preprocess a source file
src/controlmenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/controlmenu.cpp.i
.PHONY : src/controlmenu.cpp.i

src/controlmenu.s: src/controlmenu.cpp.s

.PHONY : src/controlmenu.s

# target to generate assembly for a file
src/controlmenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/controlmenu.cpp.s
.PHONY : src/controlmenu.cpp.s

src/controlmenumain.o: src/controlmenumain.cpp.o

.PHONY : src/controlmenumain.o

# target to build an object file
src/controlmenumain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/controlmenumain.cpp.o
.PHONY : src/controlmenumain.cpp.o

src/controlmenumain.i: src/controlmenumain.cpp.i

.PHONY : src/controlmenumain.i

# target to preprocess a source file
src/controlmenumain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/controlmenumain.cpp.i
.PHONY : src/controlmenumain.cpp.i

src/controlmenumain.s: src/controlmenumain.cpp.s

.PHONY : src/controlmenumain.s

# target to generate assembly for a file
src/controlmenumain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/controlmenumain.cpp.s
.PHONY : src/controlmenumain.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o

.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i

.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s

.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/options.o: src/options.cpp.o

.PHONY : src/options.o

# target to build an object file
src/options.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/options.cpp.o
.PHONY : src/options.cpp.o

src/options.i: src/options.cpp.i

.PHONY : src/options.i

# target to preprocess a source file
src/options.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/options.cpp.i
.PHONY : src/options.cpp.i

src/options.s: src/options.cpp.s

.PHONY : src/options.s

# target to generate assembly for a file
src/options.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvkbuntu-easy-menu-qt.dir/build.make CMakeFiles/dvkbuntu-easy-menu-qt.dir/src/options.cpp.s
.PHONY : src/options.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dvkbuntu-easy-menu-qt_autogen"
	@echo "... dvkbuntu-easy-menu-qt"
	@echo "... dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.o"
	@echo "... dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.i"
	@echo "... dvkbuntu-easy-menu-qt_autogen/UVLADIE3JM/qrc_resource.s"
	@echo "... dvkbuntu-easy-menu-qt_autogen/mocs_compilation.o"
	@echo "... dvkbuntu-easy-menu-qt_autogen/mocs_compilation.i"
	@echo "... dvkbuntu-easy-menu-qt_autogen/mocs_compilation.s"
	@echo "... src/controlmenu.o"
	@echo "... src/controlmenu.i"
	@echo "... src/controlmenu.s"
	@echo "... src/controlmenumain.o"
	@echo "... src/controlmenumain.i"
	@echo "... src/controlmenumain.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/options.o"
	@echo "... src/options.i"
	@echo "... src/options.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

